### PR TITLE
fallback menu active when route change cancel

### LINKED ISSUE #8229: [Bug Report] NavMenu: Problem with active menu with 'beforeRouteLeave()' vue-router
### Element UI version
2.0.4

### OS/Browsers version
Win10 / Chrome 62

### Vue version
2.5.3

### Reproduction Link
[https://jsfiddle.net/marceloavf/8xrk1n9f/310/](https://jsfiddle.net/marceloavf/8xrk1n9f/310/)

### Steps to reproduce
* Try to change the route to another page by clicking the NavMenu (/about)
* Cancel the change, the route still the same but the menu goes to the route that you have cancelled

### What is Expected?
* Follow the exactly route change, if you cancel in beforeRouteLeave, the active route should stay the same

### What is actually happening?
* It's changing the active menu to the wrong route instead stay the same

### PR DESCRIPTION
**Pull request by baiyaaaaa**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

fix #8229

### CODE REVIEW

File: packages/menu/src/menu.vue [hunk 1]
```diff
@@ -252,7 +254,10 @@
         }
 
         if (this.router) {
-          this.routeToItem(item);
+          this.routeToItem(item, error => {
+            this.activeIndex = oldActiveIndex;
+            console.error(error);
```
Comment (Leopoldthecoder) [inline packages/menu/src/menu.vue]: 这个 console 需要吗

Comment (baiyaaaaa) [reply packages/menu/src/menu.vue]: 爱要不要
