### PR TITLE
Forward fixed column's mousewheel event to entire table

### LINKED ISSUE #7339: [Bug Report] el-table not scrolling when hover a fixed column
### Element UI version
1.4.6 and 2.0.0-alpha.1 (apparently all)

### OS/Browsers version
macOS 10.12.6 / Opera 48 / Firefox 55

### Vue version
2.4.4

### Reproduction Link
[https://jsfiddle.net/pj71jkyw/758/](https://jsfiddle.net/pj71jkyw/758/)

### Steps to reproduce
Create a table element hover to a fixed column and try to scroll, it will not

### What is Expected?
It should scroll the table regardless the position of mouse cursor

### What is actually happening?
When you point the cursor on a fixed column, it will not scroll the table elements

### PR DESCRIPTION
**Pull request by furybean**
Please make sure these boxes are checked before submitting your PR, thank you!

Fix #7339.

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
在固定列上滚动，好像只能向右和向下滚动，无法向左和向上滚动：
untitled1

另外是不是最好阻止带动父元素的滚动？

**Comment by furybean** [comment]
@Leopoldthecoder done.

File: packages/table/src/table.vue [hunk 1]
```diff
@@ -294,10 +300,32 @@
...
+          }
+          bodyWrapper.scrollTop += Math.ceil(data.pixelY / 5);
+        } else {
+          bodyWrapper.scrollLeft += Math.ceil(data.pixelX / 5);
+        }
+      },
+
+      handleHeaderFooterMousewheel(event, data) {
+        event.preventDefault();
+        this.bodyWrapper.scrollLeft += data.pixelX / 5;
```
Comment (Leopoldthecoder) [inline packages/table/src/table.vue]: 这里是不是可以
```JS
const { pixelX, pixelY } = data;
if (Math.abs(pixelX) >= Math.abs(pixelY)) {
  event.preventDefault();
  this.bodyWrapper.scrollLeft += data.pixelX / 5;
}
```
