### PR TITLE
AutoComplete: fix key enter, Fixed #2632

### LINKED ISSUE #2632: autocomplete没有匹配到输入项的时候回车会报错
http://element.eleme.io/#/zh-CN/component/input

找到`输入后匹配输入建议`的input，然后输入`三`，然后回车，会报错

```
Uncaught TypeError: Cannot read property 'value' of undefined
    at a.select (element-ui.1a01327.js:3)
    at a.n [as select] (vue.runtime.min.js:6)
    at a.handleKeyEnter (element-ui.1a01327.js:3)
    at a.n [as handleKeyEnter] (vue.runtime.min.js:6)
    at Array.n.nativeOn.keydown (element-ui.1a01327.js:3)
    at HTMLDivElement.<anonymous> (vue.runtime.min.js:6)
```

### PR DESCRIPTION
**Pull request by Kingwl**
#2632

### CODE REVIEW

File: packages/autocomplete/src/autocomplete.vue [hunk 1]
```diff
@@ -19,7 +19,7 @@
       </template>
       <template slot="append" v-if="$slots.append">
         <slot name="append"></slot>
-      </template> 
+      </template>
```
Comment (reverland) [inline packages/autocomplete/src/autocomplete.vue]: 你家atom的自动行尾空格抹去233

Comment (Kingwl) [inline packages/autocomplete/src/autocomplete.vue]: 🌚
