### PR TITLE
Slider: fix a NaN value bug, fixed #1282

### LINKED ISSUE #1282: [Slider]的v-model绑定一个NaN的值 浏览器貌似会卡住
`
 <el-slider v-model="value4"">
    </el-slider>
`
今儿写到slider 赋值时候 this.value = parseInt( a ) 这个a是值是空字符串 然后chrome内存就开始无限+了 
不知是不是bug

https://jsfiddle.net/yelingfeng/5u16k232/4/

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: packages/slider/src/main.vue [hunk 1]
```diff
@@ -221,7 +221,9 @@
     },
 
     created() {
-      if (typeof this.value !== 'number' || this.value < this.min) {
+      if (typeof this.value !== 'number' ||
+        Number.isNaN(this.value) ||
```
Comment (furybean) [inline packages/slider/src/main.vue]: isNaN 是 window 的方法

Comment (Leopoldthecoder) [inline packages/slider/src/main.vue]: 哦，查了一下，`Number.isNaN` 是 ES6 的……已经更新。
