### PR TITLE
Fix Table with rowKey's expandRows collapse when data change

### LINKED ISSUE #9317: [Bug Report] should don't fold the table row with 'expand-row-keys' attribute when data update
### Element UI version
2.0.11

### OS/Browsers version
windows 7 (32 bit) / Chrome 61.0.3163.79 

### Vue version
2.5.13

### Reproduction Link
[https://codepen.io/alvinhuang/pen/rpqzXr?editors=1010](https://codepen.io/alvinhuang/pen/rpqzXr?editors=1010)

### Steps to reproduce
1. expand one row
2. click 'update data' button, you will see the row fold

### What is Expected?
should don't fold the row 

### What is actually happening?
table folded the row

### PR DESCRIPTION
**Pull request by furybean**
Fix #9317.

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: packages/table/src/table-store.js [hunk 1]
```diff
@@ -46,6 +46,7 @@ const toggleRowSelection = function(states, row, selected) {
 
 const toggleRowExpansion = function(states, row, expanded) {
   let changed = false;
+  console.log('toggleRowExpansion');
```
Comment (Leopoldthecoder) [inline packages/table/src/table-store.js]: 可删

File: packages/table/src/table-store.js [hunk 2]
```diff
@@ -405,6 +406,15 @@ TableStore.prototype.toggleRowExpansion = function(row, expanded) {
   }
 };
 
+TableStore.prototype.isRowExpanded = function(row) {
+  const { expandRows = [], rowKey } = this.states.expandRows;
```
Comment (Leopoldthecoder) [inline packages/table/src/table-store.js]: `this.states.expandRows` => `this.states`

**Comment by furybean** [comment]
@Leopoldthecoder fixed.
