### PR TITLE
Fix Tree Bug: set data does not work

### LINKED ISSUE #243: tree ：data值是动态获得，则渲染失败
<el-tree :data="data" :props="defaultProps"></el-tree>
如果data是动态获得的，不能动态渲染

### PR DESCRIPTION
**Pull request by furybean**
Fix #243

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: packages/tree/src/model/node.js [hunk 1]
```diff
@@ -69,23 +69,28 @@ export default class Node {
...
-        this.insertChild(new Node({
-          data: child,
-          parent: this,
-          lazy: this.lazy,
-          load: this.load,
-          props: this.props
-        }));
-      }
+  setData(data) {
+    this.data = data;
```
Comment (weiluxia1988) [inline packages/tree/src/model/node.js]: 需要清空this.children

Comment (furybean) [inline packages/tree/src/model/node.js]: @weiluxia1988 是的，我处理下。
