### PR TITLE
Menu: add popper-append-to-body for SubMenu

### LINKED ISSUE #10513: [Bug Report] NavMenu submenu location calculation error
### Element UI version
2.3.2

### OS/Browsers version
windows10/Chrome 65.0.3325.181（正式版本） （64 位）

### Vue version
2.5.16

### Reproduction Link
[https://jsfiddle.net/55yh8jv7/3/](https://jsfiddle.net/55yh8jv7/3/)

### Steps to reproduce
1、运行
2、鼠标移动到【我的工作台】菜单
3、鼠标移动到【选项4】菜单

### What is Expected?
【选项4】的子菜单出现在左边或者底部

### What is actually happening?
【选项4】的子菜单依然出现在右边，且屏幕宽度被撑开导致无法选择子菜单

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please make sure these boxes are checked before submitting your PR, thank you!

Resolves #10513

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: types/submenu.d.ts [hunk 1]
```diff
@@ -8,6 +8,18 @@ export declare class ElSubmenu extends ElementUIComponent {
   /** Delay time before show a sub-menu */
   showTimeout: number
 
-  /** Delay time before hide a sub-menu */
+  /** Delay time before showing a sub-menu */
+  showTimeout: number
```
Comment (jigs-patel) [inline types/submenu.d.ts]: this is duplicate, declaration.
caused module to throw error when building with webpack.
Can you please remove the duplicate declaration of type for - showTimeout form type file.

Comment (Leopoldthecoder) [reply types/submenu.d.ts]: It's already removed.
