### PR TITLE
Table: Fixed #3896

### LINKED ISSUE #3896: [Bug Report] Table内嵌进Dialog中时，筛选下拉被遮挡
### Element UI version
1.2.7

### OS/Browsers version
MacOS 10.12.4/Chrome 56.0.2924.87 (64-bit)

### Vue version
2.2.6

### Reproduction Link
[https://jsfiddle.net/ScottLeung/qq5zq3mk/5/](https://jsfiddle.net/ScottLeung/qq5zq3mk/5/)

### Steps to reproduce
1、打开dialog；
2、用标签筛选第一次后，关闭dialog；
3、再次打开dialog；
4、再次用标签筛选时z-index被盖住，问题重现。

### What is Expected?
无论多少次打开关闭dialog和多次筛选dialog中table的filter，均能正确地显示出dialog和table中的filter。

### What is actually happening?
第一次正常，之后就不行了。

### PR DESCRIPTION
**Pull request by liyanlong**
* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

解决嵌套dialog，table的filter panel 被遮罩的问题  #3896

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
@liril-net 大佬来看一眼吧

File: packages/table/src/filter-panel.vue [hunk 1]
```diff
@@ -175,6 +176,13 @@
           Dropdown.close(this);
         }
       });
+    },
+    watch: {
+      showPopper(val) {
+        if (val === true && parseInt(this.popperJS._popper.style.zIndex, 10) < PopupManager.zIndex) {
+          this.popperJS._popper.style.zIndex = PopupManager.zIndex + 1;
```
Comment (liril-net) [inline packages/table/src/filter-panel.vue]: `PopupManager.nextZIndex()`

Comment (liyanlong) [inline packages/table/src/filter-panel.vue]: 已经修改
