### PR TITLE
Tooltip: fix router-link, fixed #3042

### LINKED ISSUE #3042: 1.2.1 tooltip 里面用router-link 报错
image

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
现在的修法有问题，后面在找其他方法。。。

File: build/deploy-ci.sh [hunk 1]
```diff
@@ -42,7 +42,7 @@ if [ "$TRAVIS_TAG" ]; then
   export SUB_FOLDER=$(echo "$TRAVIS_TAG" | grep -o -E "\d+\.\d+")
   echo $SUB_FOLDER
 
-  SUB_FOLDER='1.1'
+  SUB_FOLDER='1.2'
```
Comment (Leopoldthecoder) [inline build/deploy-ci.sh]: 我改过了

Comment (QingWei-Li) [inline build/deploy-ci.sh]: 不冲突
