### PR TITLE
Cascader: fix display errors

### LINKED ISSUE #15854: [Bug Report] Cascader cascade selector displays values that are not consistent with the actual selected median
### Element UI version
2.9.1

### OS/Browsers version
Windows 64

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/huoerica/pen/ZNwLGa

### Steps to reproduce
1，选中 [ "2号厂区", "C区" ]，
2，选中[ "3号厂区", "B区" ]，

### What is Expected?
1，显示[ "2号厂区", "C区" ]，实际[ "2号厂区", "C区" ]
2，显示[ "3号厂区", "B区" ]，实际[ "3号厂区", "B区" ]

### What is actually happening?
1，显示[ "2号厂区", "C区" ]，实际[ "2号厂区", "C区" ]
2，显示[ "2号厂区", "B区" ]，实际[ "3号厂区", "B区" ]

### PR DESCRIPTION
**Pull request by junyiz**
* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

- Closes #15854

### CODE REVIEW

**Comment by ziyoung** [comment]
请解决冲突。

**Comment by junyiz** [comment]
> 请解决冲突。

已没有冲突了

File: packages/cascader-panel/src/store.js [hunk 1]
```diff
@@ -52,9 +52,8 @@ export default class Store {
 
   getNodeByValue(value) {
     if (value) {
-      value = Array.isArray(value) ? value[value.length - 1] : value;
       const nodes = this.getFlattedNodes(false, !this.config.lazy)
-        .filter(node => node.value === value);
+        .filter(node => (valueEquals(node.path, value) || node.value === value));
```
Comment (iamkun) [inline packages/cascader-panel/src/store.js]: 如果 value 是数组 这里是不是就报错了？

Comment (junyiz) [reply packages/cascader-panel/src/store.js]: 不会报错，valueEquals 就是为了比较 value 是数组的情况
