### PR TITLE
Loading: add missing definition of directive

### LINKED ISSUE #11746: [Bug Report] [Typescript] Loading directive typing missing.
### Element UI version
2.4.1

### OS/Browsers version
n/a

### Vue version
2.5.17-beta.0

### Reproduction Link
[https://jsfiddle.net/mmx38qxw/2842/](https://jsfiddle.net/mmx38qxw/2842/)

### Steps to reproduce
import `Loading` with on demand style

try use the directive by `Vue.use(Loading.directive);`

### What is Expected?
directive register properly 

### What is actually happening?
throw an error `[ts] Property 'directive' does not exist on type 'ElLoading'.`

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please make sure these boxes are checked before submitting your PR, thank you!

Closes #11746

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: types/loading.d.ts [hunk 1]
```diff
@@ -50,6 +50,8 @@ export interface ElLoading {
 
   /** If you do not have a specific DOM node to attach the Loading directive, or if you simply prefer not to use Loading as a directive, you can call this service with some configs to open a Loading instance. */
   service (options: LoadingServiceOptions): ElLoadingComponent
+
+  directive: object
```
Comment (ShaneXie) [inline types/loading.d.ts]: there is a `ElLoadingDirective ` interface above at line 37
this line isn't suppose to be `directive: ElLoadingDirective `
i'm not 100% sure tho, but please check

Comment (ShaneXie) [reply types/loading.d.ts]: and i believe there are more directives missing typings, other than this one, so better check across entire project.
