### PR TITLE
Select: fix clear on remote mode, Fixed #1355

### LINKED ISSUE #1355: bug:  select 远程搜索 clearable无效
select 远程搜索 clearable无效

[demo](http://jsfiddle.net/b86rnktp/)

### PR DESCRIPTION
**Pull request by Kingwl**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

#1355

### CODE REVIEW

File: packages/select/src/select.vue [hunk 1]
```diff
@@ -97,16 +97,19 @@
...
-            icon.addEventListener('click', this.deleteSelected);
-            addClass(icon, 'is-show-close');
-          } else {
-            icon.removeEventListener('click', this.deleteSelected);
-            removeClass(icon, 'is-show-close');
+        this.$nextTick(() => {
+          let icon = this.$el.querySelector('.el-input__icon');
+          if (icon) {
+            if (criteria) {
+              icon.addEventListener('click', this.deleteSelected);
```
Comment (QingWei-Li) [inline packages/select/src/select.vue]: 做法略奇怪

Comment (Leopoldthecoder) [inline packages/select/src/select.vue]: 嗯，可以先合了。我明天再看下这里怎么处理更好。
