### PR TITLE
Switch: fix @change timing bug, fixed #1162

### LINKED ISSUE #1162: v1.0.1，el-switch @change觸發時機似乎有誤
如以下範例([v1.0.1](https://unpkg.com/element-ui@1.0.1/lib/index.js))，照理說文字永遠應該=switch的值，但卻不然。switch在第一次切換的時候後，不會更新`onOffCopy`
[DEMO](https://jsfiddle.net/pytsao/txLdjp18/18/)

change鉤子似乎是在model被修改之前觸發？
建議把鉤子做更精確的命名：例如用 willChange, didChange，否則搞不太清楚到底值變更了沒

```
<div id="app">
  <el-switch v-model="onOff" @change="onSwitch"></el-switch>
  <p>{{ onOffCopy ? "ON" : "OFF" }}</p>
</div>

var vm = new Vue({
  el: '#app',
  data: {
    onOff:true,
    onOffCopy:true  
  },
  methods: {
    onSwitch() {
      this.onOffCopy = this.onOff;
    }
  }
});
```

此外，[v1.0.0](https://unpkg.com/element-ui@1.0.0/lib/index.js)是正常的。

### PR DESCRIPTION
**Pull request by Leopoldthecoder**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by Leopoldthecoder** [comment]
直接把 checkbox 代码拿过来了🌚

File: packages/switch/src/component.vue [hunk 1]
```diff
@@ -90,18 +89,22 @@
...
+          this.$emit('input', val);
+        }
       }
     },
     watch: {
-      value(val) {
-        this.currentValue = val;
+      value() {
         if (this.onColor || this.offColor) {
           this.handleCoreColor();
```
Comment (baiyaaaaa) [inline packages/switch/src/component.vue]: 这个方法名看不太懂，方法名要强调动作语义
