### PR TITLE
Table: make toggleAllSelection method an instance method(#14075)

### LINKED ISSUE #14075: [Bug Report] el-table method toggleAllSelection on mounted event works only for the last call
### Element UI version
2.4.11

### OS/Browsers version
OSX / Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Vue version
2.5.22

### Reproduction Link
[https://jsfiddle.net/9oxt38d6/](https://jsfiddle.net/9oxt38d6/)

### Steps to reproduce
With 2 tables, if I want to check all rows in both, I call the method `toggleAllSelection` on mounted, only the last call works

```js
mounted () {
   this.$refs.multipleTable1.toggleAllSelection() // dont work
   this.$refs.multipleTable2.toggleAllSelection() // works
}
```

### What is Expected?
All tables should be with all rows checked.
<details>
I want to start the tables with all rows selected, so, since I don't have a prop to set the wich rows should be selected, I'm trying to use the method `toggleAllSelection` on mounted phase of the component
</details>

### What is actually happening?
The last call of `toggleAllSelection` is the only one that works.
<details>
Dont matter the data or any other config, only the last one works. If I put a `setTimeout` works.

```js
mounted () {
   this.$refs.multipleTable1.toggleAllSelection() // works
   setTimeout(() => {
      this.$refs.multipleTable2.toggleAllSelection() // works
   },  100);
}
```

</details>

### PR DESCRIPTION
**Pull request by LilyWakana**
fix #14075 .
All instances of TableStore share the same toggleAllSelection method in TableStore.prototype.mutations.Since the toggleAllSelection method is a debounce function which create a closure, all TableStore's instances share the same Lexical scope while they call the toggleAllSelection method. The time interval between two tables call `toggleAllSelection` is less than the debouncing delay(10), so the first call doesn't work.

This commit make the actual toggleAllSelection method an instance method.

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: packages/table/src/table-store.js [hunk 1]
```diff
@@ -112,6 +112,35 @@ const TableStore = function(table, initialState = {}) {
     selectOnIndeterminate: false
   };
 
+  this._toggleAllSelection = debounce(10, function(states) {
```
Comment (island205) [inline packages/table/src/table-store.js]: this.toggleAllSelection=debunce(10, this._toggleAllSelection)

File: packages/table/src/table-store.js [hunk 2]
```diff
@@ -347,36 +376,9 @@ TableStore.prototype.mutations = {
...
-    });
-
-    const table = this.table;
-    if (selectionChanged) {
-      table.$emit('selection-change', selection ? selection.slice() : []);
-    }
-    table.$emit('select-all', selection);
-    states.isAllSelected = value;
-  })
+  toggleAllSelection(state) {
```
Comment (island205) [inline packages/table/src/table-store.js]: _toggleAllSelection(state) {

**Comment by island205** [comment]
@LilyWakana please move _toggleAllSelection to the prototype method

File: packages/table/src/table-store.js (hunk 2 above)
Comment (LilyWakana) [reply packages/table/src/table-store.js]: 执行toggleAllSelection方法时commit的操作是`toggleAllSelection`，所以TableStore.prototype.method要有一个同名方法toggleAllSelection。

File: packages/table/src/table-store.js (hunk 1 above)
Comment (LilyWakana) [reply packages/table/src/table-store.js]: 这里是为了避免每次实例化时都创建一个匿名函数吗？这里可以把传入debounce的函数声明成一个常量，这样在原型链也查找不到了。

**Comment by island205** [comment]
Great work, Thank you for your contributions!

**Comment by island205** [comment]
by the way:

```
let o = {
  x() {
    console.log('x')
  }
}
let x = function () {
  console.log('y')
  this.x()
}
x.call(o)
```

The best solution is: put `toggleAllSelection` to the `TableStore.prototype`,  add `this.toggleAllSelection=debunce(10, this.toggleAllSelection)` to the `TableStore` constructor funciton.

**Comment by LilyWakana** [comment]
> by the way:
> 
> ```
> let o = {
>   x() {
>     console.log('x')
>   }
> }
> let x = function () {
>   console.log('y')
>   this.x()
> }
> x.call(o)
> ```
> The best solution is: put `toggleAllSelection` to the `TableStore.prototype`, add `this.toggleAllSelection=debunce(10, this.toggleAllSelection)` to the `TableStore` constructor funciton.

got it.thank you.
