### PR TITLE
DropdownMenu: fix popper, fixed #342, #194

### LINKED ISSUE #342: Dropdown下拉菜单生命周期问题
### ElementUI version
1.0.0-rc.6 

### OS/Browers version
macOS/Chrome 53

### Vue version
2.0.1

### Reproduction Link
http://element.eleme.io/#/component/dropdown

### Steps to reproduce
* 打开官方演示站点
* 选择组件菜单，找到下拉菜单演示
* 选择click触发方式的演示，点击展开菜单
* 此时不要收起菜单，点击左边一个链接，跳转到另一路由
* 此时展开的菜单并未被销毁，出现在了屏幕的左上角

### What is Expected?
展开的菜单被销毁

### What is actually happening?
展开的菜单未被销毁

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [ ] Rebase before creating a PR to keep commit history clear.
* [ ] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

**Comment by QingWei-Li** [comment]
fixed #342, #194

File: packages/dropdown/src/dropdown-menu.vue [hunk 1]
```diff
@@ -1,39 +1,36 @@
...
+    componentName: 'ElDropdownMenu',
 
-      this.$nextTick(() => {
-        this.popper = new Popper(this.$parent.$el, this.$el, { gpuAcceleration: false, placement: `bottom-${this.menuAlign}` });
+    mixins: [Popper],
+
+    created() {
+      this.$on('visible', val => {
+        this.showPopper = val;
+        console.log(val);
```
Comment (baiyaaaaa) [inline packages/dropdown/src/dropdown-menu.vue]: console

Comment (QingWei-Li) [inline packages/dropdown/src/dropdown-menu.vue]: Done
