### PR TITLE
DatePicker: Optimize the input, fixed #484

### LINKED ISSUE #484: [BUG]DatePicker: 被禁用的日期仍然可以通过手动输入选中
### ElementUI version
1.0.0-rc.7

### OS/Browers version
 macOS/Chrome 54

### Vue version
2.0.3

### Reproduction Link
[demo](https://codepen.io/jikkai/pen/JRmKqX/)

### Steps to reproduce
1.通过disabledDate设置禁用日期
2.在DatePicker组件的输入框内输入一个已经被禁用的日期

### What is Expected?
预期不能输入已经被禁用的日期

### What is actually happening?
image

### PR DESCRIPTION
**Pull request by QingWei-Li**
Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's [Contributing Guide](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.md).
* [x] Rebase before creating a PR to keep commit history clear.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: packages/date-picker/src/panel/time-select.vue [hunk 1]
```diff
@@ -72,6 +72,14 @@
         if (this.value && val && compareTime(this.value, val) === -1) {
           this.$emit('pick');
         }
+      },
+
+      value(val, old) {
+        if (val && this.items.filter(i => i.value === val && !i.disabled).length) {
```
Comment (Leopoldthecoder) [inline packages/date-picker/src/panel/time-select.vue]: this.items.some(i => i.value === val && !i.disabled)

**Comment by Leopoldthecoder** [comment]
两个 commit 啦
