### PR TITLE
Table: fix header gutter not display

### LINKED ISSUE #17060: [Bug Report] Table - In certain circumstances, the width of table header gutter  is 0, Causing the table to be misplaced
### Element UI version
2.11.1

### OS/Browsers version
Windows10 / Chrome76

### Vue version
2.6.10

### Reproduction Link
https://codepen.io/zkangmas/pen/YzKqMEJ

### Steps to reproduce
1. table initial data value assigned to []
2. Set the width of each table-column to ensure that the horizontal scrollbar can appear after step 4.
3. Set the height attribute of the table ensures that the vertical scrollbar can appear after step 4.
4. Update the data value of the table in asynchronous mode.
5. Observe the table header gutter

### What is Expected?
The table header gutter can be set width correctly

### What is actually happening?
 The width of table header gutter  is 0

### PR DESCRIPTION
**Pull request by ziyoung**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer relative issues for you PR.

- Closes #17060

### CODE REVIEW

**Comment by ziyoung** [comment]
同时也调整了 pr #16956 的部分代码。

File: packages/table/src/table.vue [hunk 1]
```diff
@@ -383,6 +383,7 @@
       updateScrollY() {
         const changed = this.layout.updateScrollY();
         if (changed) {
+          this.layout.notifyObservers('scrollable');
```
Comment (ziyoung) [inline packages/table/src/table.vue]: @luckyCao 主要的修改在这一行。

**Comment by georgyfarniev** [comment]
Thanks, guys!
