### PR TITLE
Select: Fix (#11392 & #12327)

### LINKED ISSUE #12327: [Bug Report] input takes new line even if space is available when filterable & multiple props are true
### Element UI version
2.4.6

### OS/Browsers version
Windows 7 / Chrome 68.0.3440.106 (Official Build) (64-bit)

### Vue version
2.5.2

### Reproduction Link
[https://jsfiddle.net/akki_jat/94ba3s2p/1/](https://jsfiddle.net/akki_jat/94ba3s2p/1/)

### Steps to reproduce
Just select three options and you will see input takes the whole new line.

Note: Select 3 options

### What is Expected?
Use the available space

### What is actually happening?
Taking whole new line

### Screenshot
element_issue

### PR DESCRIPTION
**Pull request by akki-jat**
Fix for Writing space become small when collapse-tags prop is added & input takes new line even if space is available when filterable & multiple props are true

- Closes #12329 
- Closes #12327

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide ([中文](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.zh-CN.md) | [English](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.en-US.md) | [Español](https://github.com/ElemeFE/element/blob/master/.github/CONTRIBUTING.es.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer relative issues for you PR.

### CODE REVIEW

File: packages/select/src/select.vue [hunk 1]
```diff
@@ -28,7 +28,7 @@
           <span class="el-select__tags-text">+ {{ selected.length - 1 }}</span>
         </el-tag>
       </span>
-      <transition-group @after-leave="resetInputHeight" v-if="!collapseTags">
+      <transition-group @after-leave="resetInputHeight" v-if="!collapseTags" style="display: contents;">
```
Comment (jikkai) [inline packages/select/src/select.vue]: IE & Edge doesn't support `display: contents` 🤔

**Comment by akki-jat** [comment]
@jikkai changes are done as you requested. Can you review now?

File: packages/theme-chalk/src/select.scss [hunk 2]
```diff
@@ -109,7 +109,6 @@
     z-index: $--index-normal;
     top: 50%;
     transform: translateY(-50%);
-    display: flex;
     align-items: center;
```
Comment (ziyoung) [inline packages/theme-chalk/src/select.scss]: The following two lines can be deleted.

File: packages/select/src/select.vue [hunk 3]
```diff
@@ -64,7 +64,7 @@
         v-model="query"
         @input="debouncedQueryChange"
         v-if="filterable"
-        :style="{ width: inputLength + 'px', 'max-width': inputWidth - 42 + 'px' }"
```
Comment (ziyoung) [inline packages/select/src/select.vue]: When `collapse-tags` is set to `true`, there are some problems.
kapture 2018-08-16 at 11 25 36

Maybe you should not modify this line.

Comment (akki-jat) [reply packages/select/src/select.vue]: @ziyoung now check.

**Comment by akki-jat** [comment]
@jikkai I understand there is no support for **display: contents** in IE & Edge, but if I put display: contents at-least it **behaves good** in **chrome & firefox** and for **IE/Edge fallback to old behaviour**.

So I think its good to have **correct behaviour in two popular browsers** rather than having **faulty behaviour in all browsers**.

What do you think? Tell me.

**Comment by akki-jat** [comment]
@ziyoung @jikkai any response?

**Comment by akki-jat** [comment]
@ziyoung @jikkai any response?

**Comment by ziyoung** [comment]
@akki-jat Your pr does fix these issues. But I don't know whether this will create new problems.

**Comment by akki-jat** [comment]
@ziyoung do some testing, if you want. And I am telling you if anything comes regarding this I will be happy to help. But do not hesitate to fix these issues.

**Comment by wacky6** [comment]
LGTM. Nice to have progressive enhancements.

I don't mind breaking IE, since Vue 3.0 is likely to break it through use of Proxy anyway. It won't hurt to add modern browser only features, so that we can push Element users to convince their clients to use modern browsers.

**Comment by akki-jat** [comment]
@wacky6 This commit is not breaking IE, it will just just behave like it is behaving right now

File: packages/select/src/select.vue (hunk 3 above)
Comment (ziyoung) [reply packages/select/src/select.vue]: @akki-jat have you fixed it?
kapture 2018-10-09 at 15 36 08

File: packages/select/src/select.vue [hunk 4]
```diff
@@ -64,7 +64,7 @@
...
+        :style="{ 'flex-grow': '1', width: inputLength / 208 + '%', 'max-width': inputWidth - 42 + 'px' }"
```
Comment (ziyoung) [inline packages/select/src/select.vue]: If I don't modify this line, I find it also works fine. By the way, what does 208 mean?

File: packages/select/src/select.vue (hunk 3 above)
Comment (akki-jat) [reply packages/select/src/select.vue]: @ziyoung I have fixed it. Why? you still getting this behaviour?

File: packages/select/src/select.vue (hunk 4 above)
Comment (akki-jat) [reply packages/select/src/select.vue]: 208 is the width of el-select__tags (I know it should be dynamic and I am pushing new commit to make it dynamic)
& What do you mean by If I don't modify this line. (Not working with updated line?)

**Comment by akki-jat** [comment]
@ziyoung updated 208 (static width). Check now. And anything comes let me know.

File: packages/select/src/select.vue (hunk 3 above)
Comment (akki-jat) [reply packages/select/src/select.vue]: @ziyoung No, this was just **Error Reproduction Link**

Comment (ziyoung) [reply packages/select/src/select.vue]: @akki-jat I mean you can use this example to test in your development environment.

Comment (akki-jat) [reply packages/select/src/select.vue]: @ziyoung sorry I misunderstood what you said and I also test using that example and its working fine. 
### And you saying put calculating height code in timer?
I don't think it is appropriate to call a code if its not needed.

Comment (ziyoung) [reply packages/select/src/select.vue]: @akki-jat I tried it again and found that the problem still exists. 

OS/Browsers version: Mac OS X 10_13_6/Chrome/69.0.3497.100

Comment (akki-jat) [reply packages/select/src/select.vue]: @ziyoung  I don't know what is happening here, is it specific to mac? Because I tested it multiple times on windows 10 / chrome & its working perfectly fine.

Comment (akki-jat) [reply packages/select/src/select.vue]: @wacky6 / @jikkai can anyone test it? Because it is working fine on my PC. Please check it.

Comment (wacky6) [reply packages/select/src/select.vue]: Confirm it has issue when `multiple`, `collapse-tags` and `filterable` are set.

See: https://jsfiddle.net/0fj6tpvo/1/
Built against https://github.com/akki-jat/element/commit/b77e59367a8b870f6a6186ffe01a5d9ab802e2c4
Tested on macOS 10.13.6, Chrome 69

Comment (akki-jat) [reply packages/select/src/select.vue]: @wacky6 / @ziyoung test it again after taking latest.

Comment (akki-jat) [reply packages/select/src/select.vue]: @ziyoung this problem caused by **resetInputHeight()** function. When we remove a tag this function is call to determine the input height but when this method calculates the height the **( +1 )** tag is not removed ( even if there are no extra selection ). So, when it calculates height it also takes +1 tag into consideration.

Note: UI updates after **resetInputHeight()** function

Comment (ziyoung) [reply packages/select/src/select.vue]: @akki-jat @ziyoung I optimize `ElTag` component https://github.com/ziyoung/element/blob/dev/packages/tag/src/tag.vue It works fine on my computer.
